### ISSUE TITLE
Can't install plugin - PostgreSQL

### ISSUE THREAD

**Issue by alexjcollins** [verbb/navigation#11]
### Description
Can't install plugin once added.

### Steps to reproduce
1. Click to install via the Plugin Store
2. Head to Settings/Plugins and attempt to install
3. Returns 'Couldn't install plugin.'

### Additional info
- PHP version: 7.1.19
- PostgreSQL: 9.5.12
- Craft Pro: 3.0.17.1

Dump of the erroring migration. Shout if you need anything else!

```
2018-07-28 13:11:52 [147.147.64.97][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.006s). Output:
    > create table {{%navigation_nodes}} ...Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "newWindow" is of type boolean but default expression is of type integer
HINT:  You will need to rewrite or cast the expression.
The SQL being executed was: CREATE TABLE "navigation_nodes" (
	"id" integer NOT NULL,
	"elementId" integer,
	"navId" integer NOT NULL,
	"url" varchar(255),
	"type" varchar(255),
	"classes" varchar(255),
	"newWindow" boolean DEFAULT 0,
	"dateCreated" timestamp(0) NOT NULL,
	"dateUpdated" timestamp(0) NOT NULL,
	"uid" char(36) NOT NULL DEFAULT '0',
	PRIMARY KEY(id)
) (/mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE "n...')
#1 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('CREATE TABLE "n...')
#2 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /mnt/devski/vhosts/subdomains/rs/vendor/verbb/navigation/src/migrations/Install.php(45): yii\db\Migration->createTable('{{%navigation_n...', Array)
#4 /mnt/devski/vhosts/subdomains/rs/vendor/verbb/navigation/src/migrations/Install.php(22): verbb\navigation\migrations\Install->createTables()
#5 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/db/Migration.php(56): verbb\navigation\migrations\Install->safeUp()
#6 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/base/Plugin.php(138): craft\db\MigrationManager->migrateUp(Object(verbb\navigation\migrations\Install))
#8 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/services/Plugins.php(476): craft\base\Plugin->install()
#9 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/controllers/PluginsController.php(48): craft\services\Plugins->installPlugin('navigation')
#10 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#11 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('install-plugin', Array)
#14 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#15 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('plugins/install...', Array)
#16 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('plugins/install...', Array)
#17 /mnt/devski/vhosts/subdomains/rs/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /mnt/devski/vhosts/subdomains/rs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /mnt/devski/vhosts/subdomains/rs/web/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by engram-design** [comment]
Fixed in [1.0.4](https://github.com/verbb/navigation/releases/tag/1.0.4)
