### ISSUE TITLE
Can't install on Craft 3.4

### ISSUE THREAD

**Issue by proimage** [verbb/navigation#151]
### Description
When I try to install via the Plugin Store, I get a red flash error message "Can't install plugin". There are relevant lines in storage/web.log, which I'll paste below.

### Additional info
- Plugin version: 1.3.13
- Craft version: 3.4.11

```log
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] INSERT INTO `craft_plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('navigation', '1.3.13', '1.0.17', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '0184dcfd-7f64-426b-a9f4-116f3460423e')
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] INSERT INTO `craft_plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('navigation', '1.3.13', '1.0.17', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '0184dcfd-7f64-426b-a9f4-116f3460423e')
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] INSERT INTO `craft_plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('navigation', '1.3.13', '1.0.17', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '2020-05-06 20:41:07', '0184dcfd-7f64-426b-a9f4-116f3460423e')
2020-05-06 13:41:07 [-][206][-][info][craft\db\MigrationManager::migrateUp] Applying Install
2020-05-06 13:41:07 [-][206][-][trace][yii\db\Transaction::begin] Set savepoint 1
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] CREATE TABLE `craft_navigation_nodes` (
	`id` int(11) NOT NULL,
	`elementId` int(11),
	`navId` int(11) NOT NULL,
	`parentId` int(11),
	`url` varchar(255),
	`type` varchar(255),
	`classes` varchar(255),
	`urlSuffix` varchar(255),
	`customAttributes` text,
	`data` text,
	`newWindow` tinyint(1) DEFAULT FALSE,
	`deletedWithNav` tinyint(1) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0',
	PRIMARY KEY(id)
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] CREATE TABLE `craft_navigation_nodes` (
	`id` int(11) NOT NULL,
	`elementId` int(11),
	`navId` int(11) NOT NULL,
	`parentId` int(11),
	`url` varchar(255),
	`type` varchar(255),
	`classes` varchar(255),
	`urlSuffix` varchar(255),
	`customAttributes` text,
	`data` text,
	`newWindow` tinyint(1) DEFAULT FALSE,
	`deletedWithNav` tinyint(1) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0',
	PRIMARY KEY(id)
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] CREATE TABLE `craft_navigation_nodes` (
	`id` int(11) NOT NULL,
	`elementId` int(11),
	`navId` int(11) NOT NULL,
	`parentId` int(11),
	`url` varchar(255),
	`type` varchar(255),
	`classes` varchar(255),
	`urlSuffix` varchar(255),
	`customAttributes` text,
	`data` text,
	`newWindow` tinyint(1) DEFAULT FALSE,
	`deletedWithNav` tinyint(1) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0',
	PRIMARY KEY(id)
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] CREATE TABLE `craft_navigation_navs` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`structureId` int(11) NOT NULL,
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`instructions` text,
	`sortOrder` smallint(6) UNSIGNED,
	`propagateNodes` tinyint(1) DEFAULT FALSE,
	`maxNodes` int(11),
	`fieldLayoutId` int(11),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`dateDeleted` datetime NULL DEFAULT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] CREATE TABLE `craft_navigation_navs` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`structureId` int(11) NOT NULL,
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`instructions` text,
	`sortOrder` smallint(6) UNSIGNED,
	`propagateNodes` tinyint(1) DEFAULT FALSE,
	`maxNodes` int(11),
	`fieldLayoutId` int(11),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`dateDeleted` datetime NULL DEFAULT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] CREATE TABLE `craft_navigation_navs` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`structureId` int(11) NOT NULL,
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`instructions` text,
	`sortOrder` smallint(6) UNSIGNED,
	`propagateNodes` tinyint(1) DEFAULT FALSE,
	`maxNodes` int(11),
	`fieldLayoutId` int(11),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`dateDeleted` datetime NULL DEFAULT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2020-05-06 13:41:07 [-][206][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2020-05-06 13:41:07 [-][206][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.058s). Output:
    > create table {{%navigation_nodes}} ... done (time: 0.056s)
    > create table {{%navigation_navs}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_navigation_navs' already exists
The SQL being executed was: CREATE TABLE `craft_navigation_navs` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`structureId` int(11) NOT NULL,
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`instructions` text,
	`sortOrder` smallint(6) UNSIGNED,
	`propagateNodes` tinyint(1) DEFAULT FALSE,
	`maxNodes` int(11),
	`fieldLayoutId` int(11),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`dateDeleted` datetime NULL DEFAULT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8 (C:\example.com\htdocs\vendor\yiisoft\yii2\db\Schema.php:674)
#0 C:\example.com\htdocs\vendor\yiisoft\yii2\db\Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 C:\example.com\htdocs\vendor\yiisoft\yii2\db\Command.php(1093): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 C:\example.com\htdocs\vendor\yiisoft\yii2\db\Migration.php(323): yii\db\Command->execute()
#3 C:\example.com\htdocs\vendor\verbb\navigation\src\migrations\Install.php(69): yii\db\Migration->createTable('{{%navigation_n...', Array)
#4 C:\example.com\htdocs\vendor\verbb\navigation\src\migrations\Install.php(16): verbb\navigation\migrations\Install->createTables()
#5 C:\example.com\htdocs\vendor\craftcms\cms\src\db\Migration.php(52): verbb\navigation\migrations\Install->safeUp()
#6 C:\example.com\htdocs\vendor\craftcms\cms\src\db\MigrationManager.php(233): craft\db\Migration->up(true)
#7 C:\example.com\htdocs\vendor\craftcms\cms\src\base\Plugin.php(140): craft\db\MigrationManager->migrateUp(Object(verbb\navigation\migrations\Install))
#8 C:\example.com\htdocs\vendor\craftcms\cms\src\services\Plugins.php(517): craft\base\Plugin->install()
#9 C:\example.com\htdocs\vendor\craftcms\cms\src\controllers\PluginsController.php(50): craft\services\Plugins->installPlugin('navigation', 'standard')
#10 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#11 C:\example.com\htdocs\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#12 C:\example.com\htdocs\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 C:\example.com\htdocs\vendor\craftcms\cms\src\web\Controller.php(178): yii\base\Controller->runAction('install-plugin', Array)
#14 C:\example.com\htdocs\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#15 C:\example.com\htdocs\vendor\craftcms\cms\src\web\Application.php(291): yii\base\Module->runAction('plugins/install...', Array)
#16 C:\example.com\htdocs\vendor\craftcms\cms\src\web\Application.php(559): craft\web\Application->runAction('plugins/install...', Array)
#17 C:\example.com\htdocs\vendor\craftcms\cms\src\web\Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 C:\example.com\htdocs\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 C:\example.com\htdocs\web\index.php(21): yii\base\Application->run()
#20 {main}

2020-05-06 13:41:07 [-][206][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-05-06 13:41:07 [-][206][-][info][yii\db\Command::execute] DELETE FROM `craft_plugins` WHERE `handle`='navigation'
2020-05-06 13:41:07 [-][206][-][profile begin][yii\db\Command::execute] DELETE FROM `craft_plugins` WHERE `handle`='navigation'
2020-05-06 13:41:07 [-][206][-][profile end][yii\db\Command::execute] DELETE FROM `craft_plugins` WHERE `handle`='navigation'
```

**Comment by engram-design** [comment]
Its saying that there is already a `craft_navigation_navs` database table. Was this an upgrade, or you've never installed the Navigation plugin before?

Your best bet is to either delete, or rename the `craft_navigation_*` tables and try to install again.

**Comment by proimage** [comment]
Yeah, there was something screwey with the entire site DB. Restoring from a backup seems to have fixed things. Sorry, and thanks. :)
