### ISSUE TITLE
Unable to save node due to unknown property: urlSuffix

### ISSUE THREAD

**Issue by sjcallender** [verbb/navigation#165]
### Description
When trying to save either an Entry that has a node in a nav or saving a node in a nav, we're getting an error.

```
2020-06-26 16:04:36 [-][1][e05eco2p08uecmdvi6cbnub2j1][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: verbb\navigation\records\Node::urlSuffix in /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('urlSuffix', NULL)
#1 /Users/stephencallender/Projects/_sites/local-ch/vendor/verbb/navigation/src/elements/Node.php(381): yii\db\BaseActiveRecord->__set('urlSuffix', NULL)
#2 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(2027): verbb\navigation\elements\Node->afterSave(false)
#3 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(529): craft\services\Elements->_saveElementInternal(Object(verbb\navigation\elements\Node), true, false)
#4 /Users/stephencallender/Projects/_sites/local-ch/vendor/verbb/navigation/src/services/Nodes.php(80): craft\services\Elements->saveElement(Object(verbb\navigation\elements\Node), true, false)
#5 [internal function]: verbb\navigation\services\Nodes->onSaveElement(Object(craft\events\ElementEvent))
#6 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\ElementEvent))
#7 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'beforeSaveEleme...', Object(craft\events\ElementEvent))
#8 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(1884): yii\base\Component->trigger('beforeSaveEleme...', Object(craft\events\ElementEvent))
#9 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/services/Elements.php(529): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true)
#10 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/controllers/EntriesController.php(378): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#11 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#12 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-entry', Array)
#15 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#16 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/save-en...', Array)
#17 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('entries/save-en...', Array)
#18 /Users/stephencallender/Projects/_sites/local-ch/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /Users/stephencallender/Projects/_sites/local-ch/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/stephencallender/Projects/_sites/local-ch/web/index.php(21): yii\base\Application->run()
#21 /Users/stephencallender/.composer/vendor/laravel/valet/server.php(191): require('/Users/stephenc...')
#22 {main}
```

### Steps to reproduce

1. Watch this: https://ssdd.d.pr/PPKUwU

### Additional info

- Plugin version: Navigation 1.2.4
- Craft version: 3.3.20.1
(I'd love to upgrade to Craft 3.4 but we're getting an error during migration that Craft says happens because there's another (unknown) error we need to find and fix. Maybe this is it?)

**Comment by sjcallender** [comment]
Did another database refresh and Navigation plugin upgrade retry and it works this time. Must have borked something earlier.
