### ISSUE TITLE
Undefined index: name

### ISSUE THREAD

**Issue by dgtlcrftrs** [verbb/navigation#170]
### Description
For some reason this had caused a fatal error on my site with syncing project changes. Nothing is fixing it, not rebuilding or syncing the project.yaml file. I've done a trace and this came up:

```2020-07-22 10:17:39 [172.18.0.1][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: name in /var/www/html/vendor/verbb/navigation/src/services/Navs.php:200
php_1         | Stack trace:
php_1         | #0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/v...', 200)
php_1         | #1 /var/www/html/vendor/verbb/navigation/src/services/Navs.php(200): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/html/v...', 200, Array)
php_1         | #2 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1103): verbb\navigation\services\Navs->handleChangedNav(Object(craft\events\ConfigEvent))
php_1         | #3 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
php_1         | #4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
php_1         | #5 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(676): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
php_1         | #6 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1205): craft\services\ProjectConfig->processConfigChanges('navigation.navs...', false, NULL, true)
php_1         | #7 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(540): craft\services\ProjectConfig->_applyChanges(Array)
php_1         | #8 /var/www/html/vendor/craftcms/cms/src/controllers/ConfigSyncController.php(52): craft\services\ProjectConfig->applyYamlChanges()
php_1         | #9 [internal function]: craft\controllers\ConfigSyncController->actionApplyYamlChanges()
php_1         | #10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
php_1         | #11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
php_1         | #12 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('apply-yaml-chan...', Array)
php_1         | #13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('apply-yaml-chan...', Array)
php_1         | #14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('config-sync/app...', Array)
php_1         | #15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(685): craft\web\Application->runAction('config-sync/app...')
php_1         | #16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(248): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
php_1         | #17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
php_1         | #18 /var/www/html/web/index.php(29): yii\base\Application->run()
```

**Comment by engram-design** [comment]
What versions of Navigation and Craft are you on? Was this a recent upgrade? Anything changed with regards to Navigation on your sync?

**Comment by engram-design** [comment]
Are you also able to look at your project.yaml file and look for:
```
navigation:
  navs:
```

And send through the contents? From that error it looks like the name of a nav is missing..;.

**Comment by engram-design** [comment]
Closing due to inactivity
