### ISSUE TITLE
Error when adding a new site

### ISSUE THREAD

**Issue by Mosnar** [verbb/navigation#304]
### Describe the bug

When I add a new site, I receive the following error:

```
2022-07-14 12:22:30 [-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: Undefined variable $elementsService in /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/verbb/navigation/src/services/Navs.php:562
Stack trace:
#0 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/verbb/navigation/src/services/Navs.php(562): yii\base\ErrorHandler->handleError()
#1 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/verbb/navigation/src/services/Navs.php(344): verbb\navigation\services\Navs->resaveNodesForSite()
#2 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1199): verbb\navigation\services\Navs->handleChangedNav()
#3 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#4 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()
#5 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(771): yii\base\Component->trigger()
#6 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1189): craft\services\ProjectConfig->_processConfigChangesInternal()
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent()
#8 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()
#9 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(771): yii\base\Component->trigger()
#10 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(1307): craft\services\ProjectConfig->_processConfigChangesInternal()
#11 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/services/ProjectConfig.php(594): craft\services\ProjectConfig->_applyChanges()
#12 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(174): craft\services\ProjectConfig->applyYamlChanges()
#13 [internal function]: craft\console\controllers\ProjectConfigController->actionApply()
#14 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#15 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#16 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction()
#17 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction()
#18 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#19 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#20 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#21 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#22 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest()
#23 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#24 /home/ploi/<redacted>-deploy/<redacted>/25012022_162608/cms/craft(23): yii\base\Application->run()
#25 {main}
```

If I refresh, the error doesn't occur again; however, it does occur when the change is deployed and applied via `project-config/apply`

### Steps to reproduce

1. Add a new site to an existing site with existing menus
2. See error
3. Refresh error screen, no more error
4. Push changes to staging and apply project config - see error.

### Craft CMS version

Craft Pro 3.7.48

### Plugin version

1.4.27

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [1.4.28](https://github.com/verbb/navigation/releases/tag/1.4.28)
