### ISSUE TITLE
Problem when applying the project-config command.

### ISSUE THREAD

**Issue by philippe-leeroy** [verbb/navigation#401]
### Describe the bug

The `php craft project-config --force` to apply all settings throw this error: 

```
- updating entryTypes.63482388-c852-4aaf-a95d-276d540ed5ca.fieldLayouts.5092d32b-6120-46a4-bf67-ec4764bac5d1.tabs.0.elements.0 ... 
  - updating entryTypes.63482388-c852-4aaf-a95d-276d540ed5ca ... 
error: Calling unknown method: craft\console\Request::getQueryParam()
```

I've found, in the console.log - this stack : 

```
2024-08-06 16:40:41 [console.ERROR] [yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getQueryParam() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:308
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/UrlHelper.php(640): yii\base\Component->__call('getQueryParam', Array)
#1 /var/www/html/vendor/craftcms/cms/src/helpers/UrlHelper.php(351): craft\helpers\UrlHelper::_createUrl('explorer', Array, NULL, false)
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3011): craft\helpers\UrlHelper::siteUrl('explorer', NULL, NULL, 1)
#3 /var/www/html/vendor/verbb/navigation/src/services/Nodes.php(57): craft\base\Element->getUrl()
#4 [internal function]: verbb\navigation\services\Nodes->onSaveElement(Object(craft\events\ElementEvent))
...
```

When I deactivate Navigation and Hyper plugins, there is no error.

Maybe it's related to the sections that we have...

But it's weird that the Nodes->onSaveElement is not aware that the call comes from the console instead of a normal request...

### Steps to reproduce

1. Have a project with at least a single section.
2. Call the `php craft project-config --force` and wait for the error.

### Craft CMS version

4.11.0.1

### Plugin version

2.1.0

### Multi-site?

Yes

### Additional context

We also have Hyper 1.2.0

**Comment by philippe-leeroy** [comment]
Ok you can ignore this bug. Craft CMS has released 4.11.0.2 that is correcting it.
