### ISSUE TITLE
error: Invalid node ID

### ISSUE THREAD

**Issue by spAnser** [verbb/navigation#80]
### Description
Getting `error: Invalid node ID: ###` when trying to add a new node with a parent on a multi site.

Propagate nodes across all enabled sites? Enabled

Turning off propagate nodes fixes it.

It does look like it was fixed in 1.1.8 but I seem to be still experiencing it after updating to 1.1.10

### Steps to reproduce

1. Select a parent when adding a new node
2. Clicking add does nothing. You can see the error in the browser inspector.

### Additional info

- Plugin version: 1.1.10
- Craft version: 3.1.18

**Comment by engram-design** [comment]
What's the full error shown in your web console? It should have some reference to a line number and file where the error occurs.

I can't replicate  on a multi-site setup locally. Are you trying to add entry nodes, or a manual node? Is this for the primary site, or a non-primary site?

**Comment by spAnser** [comment]
Couldn't find it before but double checked again

```
2019-03-19 06:59:35 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2019-03-19 06:59:35 [-][1][-][error][TypeError] TypeError: Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, null given, called in ______/vendor/verbb/navigation/src/elements/Node.php on line 317 and defined in ______/vendor/craftcms/cms/src/services/Elements.php:194
Stack trace:
#0 ______/vendor/verbb/navigation/src/elements/Node.php(317): craft\services\Elements->getElementById(NULL, NULL, 11)
#1 ______/vendor/craftcms/cms/src/services/Elements.php(403): verbb\navigation\elements\Node->beforeSave(false)
#2 ______/vendor/craftcms/cms/src/services/Elements.php(1553): craft\services\Elements->saveElement(Object(verbb\navigation\elements\Node), true, false)
#3 ______/vendor/craftcms/cms/src/services/Elements.php(525): craft\services\Elements->_propagateElement(Object(verbb\navigation\elements\Node), true, Array)
#4 ______/vendor/verbb/navigation/src/controllers/NodesController.php(27): craft\services\Elements->saveElement(Object(verbb\navigation\elements\Node), true, true)
#5 [internal function]: verbb\navigation\controllers\NodesController->actionSaveNode()
#6 ______/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 ______/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 ______/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-node', Array)
#9 ______/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-node', Array)
#10 ______/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('navigation/node...', Array)
#11 ______/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('navigation/node...', Array)
#12 ______/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#13 ______/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 ______/web/index.php(42): yii\base\Application->run()
#15 ______/.composer/vendor/laravel/valet/server.php(158): require('______/...')
#16 {main}
```

It was happening with all nodes before must not have checked after updating, but it is just the custom url nodes now. Happens on any site not just primary.

**Comment by spAnser** [comment]
Version 1.1.11 fixed it.
